env-vars = ["TERM=xterm-256color"]
theme = "catppuccin-mocha"

# Padding-x
#
# define x axis padding (default is 0)
#
# Example:
# padding-x = 10

# Padding-y
#
# define y axis padding based on a format [top, left]
# (default is [0, 0])
#
# Example:
# padding-y = [30, 10]

confirm-before-quit = false
[cursor]
shape = 'beam'
blinking = false
blinking-interval = 800

[window]
mode = "maximized"
opacity = 1.0
blur = false
decorations = "disabled"

[renderer]
performance = "High"
backend = "Automatic"
target-fps = 144
# strategy = "Continuous"
disable-unfocused-render = false

# Keyboard
#
# use-kitty-keyboard-protocol - Enable Kitty Keyboard protocol
#
# disable-ctlseqs-alt - Disable ctlseqs with ALT keys
#   - For example: Terminal.app does not deal with ctlseqs with ALT keys
#
# Example:
[keyboard]
use-kitty-keyboard-protocol = true
# disable-ctlseqs-alt = false


[fonts]
size = 15
extras = [{ family = "Font Awesome 6 Free" }]

[fonts.regular]
family = "FiraCode Nerd Font Mono"
style = "Normal"
weight = 500

[fonts.bold]
family = "FiraCode Nerd Font Mono"
style = "Normal"
weight = 900

[fonts.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"
weight = 500

[fonts.bold-italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"
weight = 900

[colors]
light-red = "#bc5653"
light-yellow = "#ebc17a"
light-blue = "#7eaac7"
light-black = "#636363"
light-cyan = "#86d3ce"
light-white = "#f7f7f7"
light-green = "#909d63"
light-magenta = "#aa6292"
dim-background = "#202020"
light-background = "#3a3a3a"
dim-foreground = "#dbdbdb"
light-foreground = "#d9d9d9"
background = "#2c2c2c"
foreground = "#d6d6d6"
dim-blue = "#556b79"
dim-cyan = "#5c8482"
dim-magenta = "#6e4962"
dim-green = "#5e6547"
dim-white = "#828282"
dim-red = "#74423f"
dim-black = "#232323"
dim-yellow = "#8b7653"
cursor = "#d9d9d9"
text = "#2c2c2c"
white = "#cacaca"
green = "#909d63"
magenta = "#aa6292"
red = "#bc5653"
black = "#1c1c1c"
cyan = "#86d3ce"
yellow = "#ebc17a"
blue = "#7eaac7"

# Log level
#
# This property enables log level filter and file. The default level is "OFF" and the logs are not logged to a file as default.
#
# Example:
# [developer]
# log-level = "OFF"
# enable-log-file = false

